=head1 Writing Models, Views and Controllers


=head1 Controllers

%INCLUDE{"L<Apache::Voodoo::ControllerAPI>" section="overview"}%

See the L<Apache::Voodoo::ControllerAPI> for more details.
=head1 Models

%INCLUDE{"L<Apache::Voodoo::ModelAPI>" section="overview"}%

See the L<Apache::Voodoo::ModelAPI> for more details.

=head1 Views

%INCLUDE{"L<Apache::Voodoo::ViewAPI>" section="overview"}%

See the View API for more details.

