################################################################################
#
# Installation specific settings for Apache Voodoo are stored here.
# Do not edit this file directly.  Use the "voodoo-control" command instead.
#
################################################################################
package Apache::Voodoo::MyConfig;

$CONFIG = {
  'APACHE_GID' => 33,
  'APACHE_UID' => 33,
  'CODE_PATH' => 'code',
  'CONF_FILE' => 'etc/voodoo.conf',
  'CONF_PATH' => 'etc',
  'DEBUG_DBD' => [
    'dbi:SQLite:dbname=/tmp/apachevoodoo.db',
    '',
    ''
  ],
  'DEBUG_PATH' => '/debug',
  'INSTALL_PATH' => '/data/apache/sites',
  'PREFIX' => '/data/apache',
  'SESSION_PATH' => '/data/apache/session',
  'TMPL_PATH' => 'html',
  'UPDATES_PATH' => 'etc/updates'
}
;

1;
