=pod ###########################################################################

=head1 NAME

Apache::Voodoo::MyConfig - Config settings for Apache::Voodoo

=head1 SYNOPSIS

Installation specific settings for Apache Voodoo are stored here.  Do not edit this file
directly; use the supplied "voodoo-control" program instead.

=cut ###########################################################################
package Apache::Voodoo::MyConfig;

$CONFIG = {
  'APACHE_GID' => 81,
  'APACHE_UID' => 81,
  'CODE_PATH' => 'code',
  'CONF_FILE' => 'etc/voodoo.conf',
  'CONF_PATH' => 'etc',
  'DEBUG_DBD' => [
    'dbi:SQLite:dbname=/tmp/apachevoodoo.db',
    '',
    ''
  ],
  'DEBUG_PATH' => '/debug',
  'INSTALL_PATH' => '/data/apache/sites',
  'PREFIX' => '/data/apache',
  'SESSION_PATH' => '/data/apache/session',
  'TMPL_PATH' => 'html',
  'UPDATES_PATH' => 'etc/updates',
  'USE_LOG4PERL' => 1,
  'LOG4PERL_CONF' => '/data/apache/lib/perl/Apache/Voodoo/log4perl.conf'
}
;

1;

=pod ###########################################################################

=head1 AUTHOR

Maverick, //verick@smurfbaneDOTorg

=head1 COPYRIGHT

Copyright (c) 2005 Steven Edwards.  All rights reserved.

You may use and distribute Voodoo under the terms described in the LICENSE
file include in this package or L<Apache::Voodoo::license>.  The summary is
it's a legalese version of the Artistic License :)

=cut ###########################################################################
