=pod ###########################################################################

=head1 NAME

Apache::Voodoo::MyConfig

=head1 SYNOPSIS

Installation specific settings for Apache Voodoo are stored here.  Do not edit this file
directly; use the supplied "voodoo-control" program instead.

=cut ###########################################################################
package Apache::Voodoo::MyConfig;

$CONFIG = {
	PREFIX => '/data/apache',
	INSTALL_PATH => '/data/apache/sites',
	SESSION_PATH => '/data/apache/session',
	CONF_PATH => "etc",
	UPDATES_PATH => "etc/updates",
	CONF_FILE => "etc/voodoo.conf",
	TMPL_PATH => "html",
	CODE_PATH => "code",
	APACHE_UID => "81",
	APACHE_GID => "81"
};

1;

=pod ###########################################################################

=head1 AUTHOR

Maverick, /\/\averick@smurfbaneDOTorg

=head1 COPYRIGHT

Copyright (c) 2005 Steven Edwards.  All rights reserved.

You may use and distribute Voodoo under the terms described in the LICENSE 
file include in this package or L<Apache::Voodoo::license>.  The summary is
it's a legalese version of the Artistic License :)

=cut ###########################################################################
